app:
    resource: "@AppBundle/Controller/"
    type:     annotation

appBundleRoad:
    resource: "@AppBundle/Resources/config/routing/routingBundle.yml"
    prefix:   /
    
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"