security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER: ROLE_ANONYMOUS
        ROLE_GESTIONNAIRE: ROLE_USER
        ROLE_ADMIN:       [ROLE_GESTIONNAIRE, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_GESTIONNAIRE, ROLE_USER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                always_use_default_target_path : true
                default_target_path: home
                use_referer : true
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/gestionnaire/, role: ROLE_GESTIONNAIRE }
        - { path: ^/admin/, role: ROLE_ADMIN }