/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dao.NauticalClubDAO;
import dao.OwnerDAO;
import dao.ShipClassDAO;
import dao.ShipDAO;
import dao.ShipSerieDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import model.NauticalClub;
import model.Owner;
import model.Ship;
import model.ShipClass;
import model.ShipSerie;

/**
 *
 * @author afpa
 */
public class Fenetre extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre
     */
    ShipTable shipTable = new ShipTable(ShipDAO.findAll());
    public static SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    public Fenetre() {
        initComponents();
        List<Owner> owners = OwnerDAO.findAll();

        for (Owner own : owners) {
            shipOwnerCbBox.addItem(own);
        }

        List<ShipSerie> shipSerie = ShipSerieDAO.findAll();
        for (ShipSerie ss : shipSerie) {
            shipSerieCbBox.addItem(ss);
        }
        List<NauticalClub> clubs = NauticalClubDAO.findAll();
        for (NauticalClub nc : clubs) {
            nauticalClubCbBox.addItem(nc);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addOwnerDlg = new javax.swing.JDialog();
        dialogueTitleLbl = new javax.swing.JLabel();
        addOwnNameLbl = new javax.swing.JLabel();
        addOwnNameTxtFld = new javax.swing.JTextField();
        addOwnFirstNameLbl = new javax.swing.JLabel();
        addOwnFirstNameTxtFld = new javax.swing.JTextField();
        addOwnBirthDateLbl = new javax.swing.JLabel();
        addOwnBirthDateTxtFld = new javax.swing.JTextField();
        nauticalClubCbBoxLbl = new javax.swing.JLabel();
        nauticalClubCbBox = new javax.swing.JComboBox<>();
        addOwnValidBtn = new javax.swing.JButton();
        formPnl = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        shipNameTxtFldLbl = new javax.swing.JLabel();
        shipNameTxtFld = new javax.swing.JTextField();
        sailNumbTxtFldLbl = new javax.swing.JLabel();
        sailNumbTxtFld = new javax.swing.JTextField();
        shipOwnerCbBoxLbl = new javax.swing.JLabel();
        shipOwnerCbBox = new javax.swing.JComboBox<>();
        addNewOwnerBtn = new javax.swing.JButton();
        shipSerieCbBoxLbl = new javax.swing.JLabel();
        shipSerieCbBox = new javax.swing.JComboBox<>();
        shipClasseCbBoxLbl = new javax.swing.JLabel();
        shipClassCbBox = new javax.swing.JComboBox<>();
        validNewShipBtn = new javax.swing.JButton();
        shipListPnl = new javax.swing.JPanel();
        shipListTtlLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        shipListTbl = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        quitBtnMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        addOwnerDlg.setFocusCycleRoot(false);

        dialogueTitleLbl.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        dialogueTitleLbl.setText("Formulaire d'ajout d'un nouveau propriétaire");

        addOwnNameLbl.setText("Veuillez entrer le nom");

        addOwnNameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOwnNameTxtFldActionPerformed(evt);
            }
        });

        addOwnFirstNameLbl.setText("Veuillez entrer le prenom");

        addOwnFirstNameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOwnFirstNameTxtFldActionPerformed(evt);
            }
        });

        addOwnBirthDateLbl.setText("Veuillez entrer la date de naissance (yyyy-mm-dd)");

        addOwnBirthDateTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOwnBirthDateTxtFldActionPerformed(evt);
            }
        });

        nauticalClubCbBoxLbl.setText("Veuillez selectionner le club du propriétaire");

        nauticalClubCbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nauticalClubCbBoxActionPerformed(evt);
            }
        });

        addOwnValidBtn.setText("Valider");
        addOwnValidBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOwnValidBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addOwnerDlgLayout = new javax.swing.GroupLayout(addOwnerDlg.getContentPane());
        addOwnerDlg.getContentPane().setLayout(addOwnerDlgLayout);
        addOwnerDlgLayout.setHorizontalGroup(
            addOwnerDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOwnerDlgLayout.createSequentialGroup()
                .addGroup(addOwnerDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addOwnerDlgLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(dialogueTitleLbl))
                    .addGroup(addOwnerDlgLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(addOwnerDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nauticalClubCbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addOwnNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addOwnFirstNameLbl)
                            .addComponent(addOwnBirthDateLbl)
                            .addComponent(addOwnBirthDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addOwnerDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(addOwnNameTxtFld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                .addComponent(addOwnFirstNameTxtFld, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(nauticalClubCbBoxLbl)))
                    .addGroup(addOwnerDlgLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(addOwnValidBtn)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        addOwnerDlgLayout.setVerticalGroup(
            addOwnerDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOwnerDlgLayout.createSequentialGroup()
                .addComponent(dialogueTitleLbl)
                .addGap(27, 27, 27)
                .addComponent(addOwnNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addOwnNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addOwnFirstNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addOwnFirstNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addOwnBirthDateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addOwnBirthDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(nauticalClubCbBoxLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nauticalClubCbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(addOwnValidBtn))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        formPnl.setPreferredSize(new java.awt.Dimension(550, 626));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ajout d'un nouveau navire", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 18))); // NOI18N

        shipNameTxtFldLbl.setText("Veuillez entrer le nom du navire");
        shipNameTxtFldLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        shipNameTxtFld.setName(""); // NOI18N

        sailNumbTxtFldLbl.setText("Veuillez entrer le numéro de voile du voilier");
        sailNumbTxtFldLbl.setAlignmentX(5.0F);

        shipOwnerCbBoxLbl.setText("Veuillez selectionner le propritaire du voilier");

        shipOwnerCbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipOwnerCbBoxActionPerformed(evt);
            }
        });

        addNewOwnerBtn.setText("Ajouter");
        addNewOwnerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewOwnerBtnActionPerformed(evt);
            }
        });

        shipSerieCbBoxLbl.setText("Veuillez selectionner la série du voilier");

        shipSerieCbBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shipSerieCbBoxItemStateChanged(evt);
            }
        });
        shipSerieCbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipSerieCbBoxActionPerformed(evt);
            }
        });

        shipClasseCbBoxLbl.setText("Veuillez entrer la classe du voilier");

        shipClassCbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipClassCbBoxActionPerformed(evt);
            }
        });

        validNewShipBtn.setText("Valider");
        validNewShipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validNewShipBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(validNewShipBtn))
                    .addComponent(shipClassCbBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shipClasseCbBoxLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sailNumbTxtFld, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sailNumbTxtFldLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addComponent(shipNameTxtFld, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(shipNameTxtFldLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shipSerieCbBoxLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shipSerieCbBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(shipOwnerCbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addNewOwnerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(shipOwnerCbBoxLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(shipNameTxtFldLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shipNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sailNumbTxtFldLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sailNumbTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(shipOwnerCbBoxLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shipOwnerCbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewOwnerBtn))
                .addGap(18, 18, 18)
                .addComponent(shipSerieCbBoxLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shipSerieCbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(shipClasseCbBoxLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shipClassCbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validNewShipBtn))
        );

        javax.swing.GroupLayout formPnlLayout = new javax.swing.GroupLayout(formPnl);
        formPnl.setLayout(formPnlLayout);
        formPnlLayout.setHorizontalGroup(
            formPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPnlLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        formPnlLayout.setVerticalGroup(
            formPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPnlLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(formPnl);

        shipListTtlLbl.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        shipListTtlLbl.setText("Liste des navires");

        shipListTbl.setModel(shipTable);
        jScrollPane1.setViewportView(shipListTbl);

        javax.swing.GroupLayout shipListPnlLayout = new javax.swing.GroupLayout(shipListPnl);
        shipListPnl.setLayout(shipListPnlLayout);
        shipListPnlLayout.setHorizontalGroup(
            shipListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shipListPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shipListPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shipListTtlLbl)
                .addGap(182, 182, 182))
        );
        shipListPnlLayout.setVerticalGroup(
            shipListPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shipListPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shipListTtlLbl)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(shipListPnl);

        jMenu1.setText("File");

        quitBtnMenuItem.setText("Quitter");
        quitBtnMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(quitBtnMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validNewShipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validNewShipBtnActionPerformed
        String shipName = shipNameTxtFld.getText();
        int sailNum = Integer.parseInt(sailNumbTxtFld.getText());
        Owner owner = (Owner) shipOwnerCbBox.getSelectedItem();
        ShipClass sc = (ShipClass) shipClassCbBox.getSelectedItem();

        Ship ship = new Ship(sailNum, shipName, sc, owner);

        try {
            ShipDAO.insert(ship);
            shipNameTxtFld.setText(null);
            sailNumbTxtFld.setText(null);
            shipTable.addShip(ship);
        } catch (Exception ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_validNewShipBtnActionPerformed

    private void shipOwnerCbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipOwnerCbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shipOwnerCbBoxActionPerformed

    private void shipClassCbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipClassCbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shipClassCbBoxActionPerformed

    private void quitBtnMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnMenuItemActionPerformed
        dispose();
    }//GEN-LAST:event_quitBtnMenuItemActionPerformed

    private void shipSerieCbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipSerieCbBoxActionPerformed

    }//GEN-LAST:event_shipSerieCbBoxActionPerformed

    private void shipSerieCbBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shipSerieCbBoxItemStateChanged
        ShipSerie ss_selected = (ShipSerie) shipSerieCbBox.getSelectedItem();
        int ser_id = ss_selected.getSer_id();
        List<ShipClass> shipClasses = ShipClassDAO.findBySerieId(ser_id);
        shipClassCbBox.removeAllItems();
        for (ShipClass sc : shipClasses) {
            shipClassCbBox.addItem(sc);
        }
    }//GEN-LAST:event_shipSerieCbBoxItemStateChanged

    private void addNewOwnerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewOwnerBtnActionPerformed
        addOwnerDlg.setSize(300, 530);
        addOwnerDlg.setResizable(false);
        addOwnerDlg.pack();
        addOwnerDlg.setLocationRelativeTo(this);
        addOwnerDlg.setVisible(true);
        
    }//GEN-LAST:event_addNewOwnerBtnActionPerformed

    private void addOwnFirstNameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOwnFirstNameTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOwnFirstNameTxtFldActionPerformed

    private void addOwnNameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOwnNameTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOwnNameTxtFldActionPerformed

    private void nauticalClubCbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nauticalClubCbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nauticalClubCbBoxActionPerformed

    private void addOwnValidBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOwnValidBtnActionPerformed
        String ownerName = addOwnNameTxtFld.getText();
        String ownerFirstName = addOwnFirstNameTxtFld.getText();
        NauticalClub club = (NauticalClub) nauticalClubCbBox.getSelectedItem();
        int club_id = club.getClub_id();
        String birthDate = addOwnBirthDateTxtFld.getText();   
        Date test= null;
        try {
            test = sdf.parse(birthDate);
        } catch (ParseException ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
        Owner o = new Owner(club_id, ownerName, ownerFirstName, test);
        try {
            OwnerDAO.insert(o);
            
        } catch (Exception ex) {
            Logger.getLogger(Fenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addOwnValidBtnActionPerformed

    private void addOwnBirthDateTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOwnBirthDateTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOwnBirthDateTxtFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    public ShipTable getShipTable() {
        return shipTable;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewOwnerBtn;
    private javax.swing.JLabel addOwnBirthDateLbl;
    private javax.swing.JTextField addOwnBirthDateTxtFld;
    private javax.swing.JLabel addOwnFirstNameLbl;
    private javax.swing.JTextField addOwnFirstNameTxtFld;
    private javax.swing.JLabel addOwnNameLbl;
    private javax.swing.JTextField addOwnNameTxtFld;
    private javax.swing.JButton addOwnValidBtn;
    private javax.swing.JDialog addOwnerDlg;
    private javax.swing.JLabel dialogueTitleLbl;
    private javax.swing.JPanel formPnl;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<NauticalClub> nauticalClubCbBox;
    private javax.swing.JLabel nauticalClubCbBoxLbl;
    private javax.swing.JMenuItem quitBtnMenuItem;
    private javax.swing.JTextField sailNumbTxtFld;
    private javax.swing.JLabel sailNumbTxtFldLbl;
    private javax.swing.JComboBox<ShipClass> shipClassCbBox;
    private javax.swing.JLabel shipClasseCbBoxLbl;
    private javax.swing.JPanel shipListPnl;
    private javax.swing.JTable shipListTbl;
    private javax.swing.JLabel shipListTtlLbl;
    private javax.swing.JTextField shipNameTxtFld;
    private javax.swing.JLabel shipNameTxtFldLbl;
    private javax.swing.JComboBox<Owner> shipOwnerCbBox;
    private javax.swing.JLabel shipOwnerCbBoxLbl;
    private javax.swing.JComboBox<ShipSerie> shipSerieCbBox;
    private javax.swing.JLabel shipSerieCbBoxLbl;
    private javax.swing.JButton validNewShipBtn;
    // End of variables declaration//GEN-END:variables
}
